apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: docker.io/envoyproxy
    chart: gateway-helm
    targetRevision: v1.9.1
    helm:
      releaseName: envoy-gateway
      # CRDs come from the envoy-gateway-crds Application.
      skipCrds: true
  destination:
    {{- include "apps.destination" "envoy-gateway-system" | nindent 4 }}
  syncPolicy:
    {{- include "apps.syncPolicy" . | nindent 4 }}
