apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.revision }}
    path: manifests/gateway
  destination:
    {{- include "apps.destination" "envoy-gateway-system" | nindent 4 }}
  syncPolicy:
    {{- include "apps.syncPolicy" . | nindent 4 }}
