apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    chart: metrics-server
    targetRevision: 3.14.0
    helm:
      releaseName: metrics-server
      valuesObject:
        args:
          # kind's kubelets serve self-signed certificates.
          - --kubelet-insecure-tls
  destination:
    {{- include "apps.destination" "kube-system" | nindent 4 }}
  syncPolicy:
    {{- include "apps.syncPolicy" . | nindent 4 }}
